version: "3.4"

services:
  walter-code-node:
    image: walter-code-node
    ports:
    - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
